### PR TITLE
Step 4 work

### PR DESCRIPTION
**Pull request by Dsl03**
**What is the purpose of this PR?**
**What changes did you make? Why?**
**What bugs did you find while testing?**
First part of my changes for Step-4. Refactors the code by using the Sieve of Eratosthenes algorithm to speed up prime factorization which helps reduces the speed for the disaster code.

First set of changes:
Average execution time after 5 runs: 0.001671 seconds

Second set of changes:
Average execution time after 5 runs: 0.000532 seconds

### CODE REVIEW

**Comment by echavemann** [comment]
screenshot?

**Comment by Dsl03** [comment]
Screenshot 2023-10-15 at 17 06 26

**Comment by echavemann** [comment]
bruh thats not fintechclub lol

**Comment by Dsl03** [comment]
Lmaooo, mb didn't read the fintech part

**Review by echavemann — APPROVED** [review]

**Pull request merged**
